// Generated by CoffeeScript 1.7.1
(function() {
  var Message, Room, Sequelize, User, messages, sequelize;

  Sequelize = require('sequelize');

  sequelize = new Sequelize('chat', 'root', 'batterchalks');

  User = sequelize.define('User', {
    username: Sequelize.STRING
  });

  Room = sequelize.define('Room', {
    roomname: Sequelize.STRING
  });

  Message = sequelize.define('Message', {
    text: Sequelize.STRING
  });

  User.hasMany(Message);

  Room.hasMany(Message);

  Message.belongsTo(User);

  Message.belongsTo(Room);

  User.sync().done(function(err) {
    if (err) {
      throw err;
    }
  });

  Room.sync().done(function(err) {
    if (err) {
      throw err;
    }
  });

  Message.sync().done(function(err) {
    if (err) {
      throw err;
    }
  });

  messages = module.exports;

  messages.add = function(message, callback) {
    var key, _i, _len, _ref;
    _ref = ['username', 'roomname', 'text'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      if (message[key] == null) {
        message[key] = '';
      }
    }
    return User.findOrCreate({
      username: message.username
    }).done(function(err, user) {
      return Room.findOrCreate({
        roomname: message.roomname
      }).done(function(err, room) {
        var newMessage;
        newMessage = Message.build({
          UserId: user.dataValues.id,
          RoomId: room.dataValues.id,
          text: message.text
        });
        return newMessage.save().done(callback);
      });
    });
  };

  messages.get = function(roomname, callback) {
    var options;
    options = {
      attributes: ['User.username', 'Room.roomname', 'text', 'createdAt'],
      include: [User, Room],
      order: 'createdAt DESC',
      limit: 100
    };
    if (roomname != null) {
      options.where = {
        'Room.roomname': roomname
      };
    }
    return Message.findAll(options).done(callback);
  };

}).call(this);

//# sourceMappingURL=messages.map
