// Generated by CoffeeScript 1.7.1
(function() {
  var Message, Sequelize, messages, sequelize;

  Sequelize = require('sequelize');

  sequelize = new Sequelize('chat', 'root', 'batterchalks');

  Message = sequelize.define('Message', {
    username: Sequelize.STRING,
    roomname: Sequelize.STRING,
    text: Sequelize.STRING
  });

  messages = module.exports;

  messages.sync = function(callback) {
    return Message.sync().done(callback);
  };

  messages.add = function(message, callback) {
    var key, newMessage, _i, _len, _ref;
    _ref = ['username', 'roomname', 'text'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      if (message[key] == null) {
        message[key] = '';
      }
    }
    newMessage = Message.build(message);
    return newMessage.save().done(callback);
  };

  messages.get = function(roomname, callback) {
    var options;
    options = {
      order: 'createdAt DESC',
      limit: 100
    };
    if (roomname != null) {
      options.where = {
        roomname: roomname
      };
    }
    return Message.findAll(options).done(callback);
  };

}).call(this);

//# sourceMappingURL=messages.map
