// Generated by CoffeeScript 1.7.1
(function() {
  var dbConnection, messages, mysql;

  mysql = require('mysql');

  dbConnection = mysql.createConnection({
    user: "root",
    password: "batterchalks",
    database: "chat"
  });

  dbConnection.connect();

  messages = module.exports;

  messages.add = function(message, callback) {
    var key, queryString, _i, _len, _ref;
    _ref = ['username', 'roomname', 'text'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      if (message[key] == null) {
        message[key] = '';
      }
    }
    message.createdAt = (new Date()).toJSON();
    queryString = "INSERT INTO messages (username, roomname, text, createdAt) VALUES ('" + message.username + "', '" + message.roomname + "', '" + message.text + "', '" + message.createdAt + "');";
    return dbConnection.query(queryString, callback);
  };

  messages.get = function(roomname, callback) {
    var queryString;
    queryString = "SELECT username, roomname, text FROM messages " + (roomname != null ? "WHERE roomname = '" + roomname + "'" : "") + " ORDER BY createdAt DESC LIMIT 10;";
    return dbConnection.query(queryString, callback);
  };

}).call(this);

//# sourceMappingURL=messages.map
